In [16]:
import numpy as np

In [2]:
list=[1,2,3,4,4,5]

In [5]:
npar=np.array(list)

In [102]:
mul=[[1,2,3],[4,5,6],[66,7,77]]
mul

[[1, 2, 3], [4, 5, 6], [66, 7, 77]]

In [105]:
np.array(mul)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [66,  7, 77]])

In [59]:
np.arange(0,100,5)   # like for loop

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [60]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
#np.zeros(4)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [28]:
np.eye(5)  #get idenety matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.random.rand(5)    #get value from 0 to 1

array([0.09563042, 0.67246489, 0.66697862, 0.23079664, 0.30651137])

In [32]:
np.random.rand(3,4)

array([[0.80810311, 0.84247066, 0.05205363, 0.84944929],
       [0.57169925, 0.9448995 , 0.52468813, 0.49186376],
       [0.39634795, 0.78964742, 0.58987088, 0.84184904]])

In [34]:
np.random.randn(3)     # get number from standard distribution

array([-1.57349341, -1.80395645,  0.34616424])

In [36]:
np.random.randn(2,3)

array([[-0.22511072, -0.30283265, -0.94861823],
       [-0.06177641, -1.27981885, -1.01162562]])

In [63]:
np.random.randint(40)   # print one random integer from 0 to 40

39

In [64]:
np.random.randint(30,100)   # print one random integer from 30 to 100

84

In [65]:
np.random.randint(30,100,5)  # get 5 random integers from 30 to 100

array([62, 68, 41, 48, 78])

In [164]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [165]:
arr.shape

(25,)

In [166]:
mul=arr.reshape(5,5)
mul

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [167]:
mul.shape           # get shape of array or matrix

(5, 5)

In [168]:
mul.dtype           # get datatype of array or matrix

dtype('int32')

In [171]:
np.__version__

'1.20.1'

In [169]:
mul.max()          # get max in array or matrix

24

In [111]:
mul.min()          # get min in array or matrix

0

In [112]:
mul.argmax()      # get max index of array or matrix

24

In [113]:
mul.argmin()    # get min index of array or matrix

0

In [18]:
a=[11,2,2,3,34,5,5,4,5,6,7,8,9]

In [19]:
arr=np.array(a)

In [26]:
s=arr[0:5]

In [27]:
s[:]=10

In [28]:
arr

array([10, 10, 10, 10, 10,  5,  5,  4,  5,  6,  7,  8,  9])

In [39]:
arr_copy=arr.copy()       #copy the arry or matrix

In [34]:
s=arr_copy[0:5]
s

array([10, 10, 10, 10, 10])

In [36]:
s[:]=30

In [37]:
arr_copy

array([30, 30, 30, 30, 30,  5,  5,  4,  5,  6,  7,  8,  9])

In [38]:
arr

array([10, 10, 10, 10, 10,  5,  5,  4,  5,  6,  7,  8,  9])

## slicing

In [40]:
a=[[1,2,3],[4,5,6],[7,8,9]]

In [43]:
arr=np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr[0][0]

1

In [52]:
arr[0,0]                 # both above row and this row are equal

1

In [53]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [55]:
arr[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [59]:
arr[:,:1]         # we get only column 1

array([[1],
       [4],
       [7]])

In [61]:
arr[:1,:]       # we get only row 1

array([[1, 2, 3]])

In [64]:
arr=np.arange(50).reshape(5,10)

In [65]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [67]:
arr[:,7:]

array([[ 7,  8,  9],
       [17, 18, 19],
       [27, 28, 29],
       [37, 38, 39],
       [47, 48, 49]])

In [68]:
arr[2:,2:5]

array([[22, 23, 24],
       [32, 33, 34],
       [42, 43, 44]])

In [69]:
arr[2:3,:]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [70]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

## numpy operations 

In [71]:
s=np.arange(20)

In [72]:
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [73]:
s+s

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [74]:
s-s

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [75]:
s/s

C:\Users\manoj\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [121]:
1/s

C:\Users\manoj\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [76]:
s*s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [77]:
s**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361], dtype=int32)

In [78]:
s+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119])

In [79]:
s-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85,  -84,  -83,  -82,  -81])

## main operations 

In [80]:
s.max()          # max value 

19

In [100]:
s.min()          # min value

0

In [157]:
s.sum()

190

In [89]:
s.mean()        # mean or average

9.5

In [84]:
s.std()       #standard deviation

5.766281297335398

In [106]:
s.var()       # variance

33.25

In [90]:
np.median(s)    # median of array

9.5

In [98]:
from scipy import stats             # to get mode 

speed = [99,86,87,88,111,86,103,87,94,78,77,85,86,94]

x = stats.mode(speed)

print(x)

ModeResult(mode=array([86]), count=array([3]))


##             Exersices

In [122]:
import numpy as np

In [124]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [126]:
ar1=np.ones(10)
ar1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [130]:
ar2=np.ones(10)*5
ar2

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [131]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [135]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [132]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [134]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [137]:
np.random.rand(1)

array([0.63588278])

In [138]:
np.random.randn(25)

array([ 0.00776953,  0.17307212,  0.37565158, -0.57163424, -1.75649617,
       -0.96142801, -0.22317661, -0.09345668,  0.72182974,  0.83646941,
        0.32216737, -0.79648646,  0.7370299 ,  1.69308541, -0.57339571,
        0.42948469, -0.67252797, -0.19796068, -0.40295421,  1.09685021,
        1.1449885 , -0.94253973,  1.77163808,  0.92072305,  0.99474157])

In [143]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [147]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [148]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [150]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [151]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [152]:
mat[3:4,4:]

array([[20]])

In [154]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [155]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [158]:
mat.sum()

325

In [159]:
mat.std()

7.211102550927978

In [160]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

In [181]:
a=np.arange(8).reshape(4,2)
b=np.arange(8).reshape(4,2)
print(a)
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [195]:
k=np.concatenate((a,b),axis=1)
k

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7]])

In [198]:
np.where(k>0,k,0)

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7]])

In [194]:
k.sort()
k

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5],
       [6, 6, 7, 7]])

In [207]:
k.tolist().index(0)

ValueError: 0 is not in list

In [208]:
k

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7]])

In [216]:
k = np.random.randint(3,30,20).reshape(4,5)

In [217]:
k

array([[18,  6, 27, 10, 13],
       [26, 19, 14, 14, 17],
       [23, 16,  4,  8,  8],
       [27, 25,  6, 14, 18]])

In [220]:
k[3]

array([27, 25,  6, 14, 18])

In [227]:
k[3].argsort()

array([2, 3, 4, 1, 0], dtype=int64)

In [231]:
k.sort()

In [232]:
k

array([[ 6, 10, 13, 18, 27],
       [14, 14, 17, 19, 26],
       [ 4,  8,  8, 16, 23],
       [ 6, 14, 18, 25, 27]])

In [251]:
l = np.random.randint(3,30,200).reshape(5,5,8)
l

array([[[22, 17, 29, 23, 16,  3, 28, 24],
        [15, 16, 11, 27, 17,  5, 15, 26],
        [ 5, 10, 10, 19,  9, 29, 13,  4],
        [15, 25,  3, 20,  4, 10,  7, 25],
        [19, 19, 21, 20, 17,  7, 26, 16]],

       [[ 4, 17,  8, 28,  9, 25,  6, 16],
        [21, 16, 27, 17,  3, 10, 17, 10],
        [16, 17, 17, 19,  6, 16,  4, 16],
        [ 8, 15, 14, 11, 17, 16,  6,  4],
        [25, 13, 15, 21, 14, 13, 23,  9]],

       [[ 6, 15, 14, 24, 22,  3, 28, 25],
        [19, 26, 27, 18, 29, 11, 11, 29],
        [ 3, 24, 20, 24, 15, 19,  6, 27],
        [17, 20,  8, 20, 18, 20, 15, 25],
        [20, 17, 21, 13, 20,  8, 27, 21]],

       [[ 9,  4, 23, 13, 20, 16,  5, 20],
        [19, 18, 29, 29,  9, 18, 10, 26],
        [ 6, 11, 20, 18, 22, 25, 24, 11],
        [ 9, 14, 29,  8, 14, 13, 29,  5],
        [16, 15, 23, 15,  5, 27,  8, 12]],

       [[22, 18, 28, 28, 25, 27,  9, 18],
        [11, 25, 14, 18, 12,  3, 21, 22],
        [15, 19,  5, 20, 22, 27, 27, 20],
        [10,  3, 18, 27, 2

In [286]:
s1=[[l[0,0,0],l[0,0,7]],[l[0,4,0],l[0,4,7]]]
s1=np.array(s1)
s1

array([[22, 24],
       [19, 16]])

In [281]:
s2=[[l[1,0,0],l[1,0,7]],[l[1,4,0],l[1,4,7]]]
s2

[[4, 16], [25, 9]]

In [282]:
s3=[[l[2,0,0],l[2,0,7]],[l[2,4,0],l[2,4,7]]]
s3

[[6, 25], [20, 21]]

In [283]:
s4=[[l[3,0,0],l[3,0,7]],[l[3,4,0],l[3,4,7]]]
s4

[[9, 20], [16, 12]]

In [291]:
s5=[[l[4,0,0],l[4,0,7]],[l[4,4,0],l[4,4,7]]]
s5

[[22, 18], [10, 7]]

In [290]:
a=[]
for x in range(5):
    s=[[l[x,0,0],l[x,0,7]],[l[x,4,0],l[x,4,7]]]
    a.append(s)
np.array(a)

array([[[22, 24],
        [19, 16]],

       [[ 4, 16],
        [25,  9]],

       [[ 6, 25],
        [20, 21]],

       [[ 9, 20],
        [16, 12]],

       [[22, 18],
        [10,  7]]])