In [1]:
import pandas as pd
import numpy as np

In [42]:
df=pd.read_csv('https://raw.githubusercontent.com/tiepvupsu/DecisionTreeID3/master/weather.csv')

In [43]:
df

id   outlook temperature humidity    wind play
0    1     sunny         hot     high    weak   no
1    2     sunny         hot     high  strong   no
2    3  overcast         hot     high    weak  yes
3    4     rainy        mild     high    weak  yes
4    5     rainy        cool   normal    weak  yes
5    6     rainy        cool   normal  strong   no
6    7  overcast        cool   normal  strong  yes
7    8     sunny        mild     high    weak   no
8    9     sunny        cool   normal    weak  yes
9   10     rainy        mild   normal    weak  yes
10  11     sunny        mild   normal  strong  yes
11  12  overcast        mild     high  strong  yes
12  13  overcast         hot   normal    weak  yes
13  14     rainy        mild     high  strong   no

In [17]:
df['play'].value_counts()

yes    9
no     5
Name: play, dtype: int64

In [68]:
yes=sum(df['play']=='yes')
yes

9

In [67]:
no=sum(df['play']=='no')
no

5

In [66]:
total=len(df['play'])
total

14

In [71]:
y=(-yes/total)*np.log2(yes/total)
y

0.40977637753840185

In [70]:
n=(-no/total)*np.log2(no/total)
n

0.5305095811322292

In [74]:
play=y+n

In [75]:
play

0.9402859586706311

In [76]:
sy=sum(df[df['outlook']=='sunny']['play']=='yes')

In [77]:
sn=sum(df[df['outlook']=='sunny']['play']=='no')

In [54]:
ss=sum(df['outlook']=='sunny')

In [78]:
syy=(-sy/ss)*np.log2(sy/ss)

In [79]:
snn=(-sn/ss)*np.log2(sn/ss)

In [80]:
sunny=syy+snn

In [81]:
sunny

0.9709505944546686

In [84]:
oy=sum(df[df['outlook']=='overcast']['play']=='yes')

In [86]:
on=sum(df[df['outlook']=='overcast']['play']=='no')

In [94]:
os=sum(df['outlook']=='overcast')

In [95]:
oyy=(-oy/os)*np.log2(oy/os)

In [96]:
onn=(-oy/os)*np.log2(oy/os)

In [97]:
overcast=oyy+onn
overcast

-0.0

In [100]:
ry=sum(df[df['outlook']=='rainy']['play']=='yes')

In [101]:
rn=sum(df[df['outlook']=='rainy']['play']=='no')

In [102]:
rs=sum(df['outlook']=='rainy')

In [103]:
ryy=(-ry/rs)*np.log2(ry/rs)

In [107]:
rnn=(-rn/rs)*np.log2(rn/rs)

In [108]:
rainy=ryy+rnn

In [109]:
rainy

0.9709505944546686

In [110]:
gain=play-((5/14)*sunny)-((4/14)*overcast)-((5/14)*rainy)

In [111]:
gain

0.24674981977443933

In [117]:
np.arange(0,100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [151]:
a=[10,20,30,40]

In [147]:
b=np.array(a)

In [150]:
i=0
x=[]
while i<4:
    x.append(a)
    a[i]=0
    i=i+1
print(x)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


In [188]:
a=list(map(int,input().split()))

10 20 30 40


In [202]:
a=list(map(int,input().split()))
s=a.copy()
b=[]
i=0
for y in range(len(a)-1):
    a[y]=0
    for x in range(len(a)):
        b.append(a[x])
k=s+b
z=np.array(k).reshape(len(a),len(a))
print(z) 

1 2 3 4 5
[[1 2 3 4 5]
 [0 2 3 4 5]
 [0 0 3 4 5]
 [0 0 0 4 5]
 [0 0 0 0 5]]


In [205]:
np.triu([10,20,30,40,50,60,70])

array([[10, 20, 30, 40, 50, 60, 70],
       [ 0, 20, 30, 40, 50, 60, 70],
       [ 0,  0, 30, 40, 50, 60, 70],
       [ 0,  0,  0, 40, 50, 60, 70],
       [ 0,  0,  0,  0, 50, 60, 70],
       [ 0,  0,  0,  0,  0, 60, 70],
       [ 0,  0,  0,  0,  0,  0, 70]])

In [227]:
np.array(pd.DataFrame(np.eye(10)).replace(1.0,10)).astype('int')


array([[10,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 10,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 10,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 10,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 10,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 10,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 10,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 10,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 10,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 10]])

In [215]:
np.empty((3,3))

array([[1.5e-323, 2.0e-323, 2.5e-323],
       [3.5e-323, 4.4e-323, 4.9e-323],
       [5.4e-323, 5.9e-323, 6.4e-323]])

In [217]:
f = np.full((4,4),10)

In [219]:
np.diag(f)

array([10, 10, 10, 10])

In [228]:
np.eye(4)*10

array([[10.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.],
       [ 0.,  0.,  0., 10.]])